default: &default
  debug: false
  api_key: <get one from openweathermap.com/api>
  zip: 72712  

development:
  <<: *default
  
test:
  <<: *default
  debug: true

production:
  <<: *default
  
